repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-autoflake
    rev: v1.7.0
    hooks:
    -   id: autoflake
        args: ['--remove-all-unused-imports', '--remove-unused-variables', '--in-place']

-   repo: https://github.com/pre-commit/mirrors-flake8
    rev: v3.10.0
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-commitizen
    rev: v2.22.0
    hooks:
    -   id: commitizen
        args: ['-n']

-   repo: https://github.com/pre-commit/mirrors-cz-conventional-changelog
    rev: v3.1.0
    hooks:
    -   id: cz-conventional-changelog
