version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - 8000:8000
    networks:
      - AIservice
    volumes:
      - ./app:/app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 3000:3000
    networks:
      - AIservice
    depends_on:
      - app

networks:
  AIservice:
    external: true
